version: '3.8'

services:
    dev-db:
        image: postgres:12-alpine
        ports:
            - '5434:5432'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=nest
        networks:
            - web-api
    test-db:
        image: postgres:12-alpine
        ports:
            - '5435:5432'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=nest
        networks:
            - web-api

networks:
    web-api:
        name: web-api
        driver: bridge
